project:
  type: website
  output-dir: docs

website:
  title: "Externalidades Espaciales"
  navbar:
    background: primary
    right: # Alineación a la derecha
      - href: index.qmd
        text: "Descripción del Problema"
      - href: teoria.qmd
        text: "Marco Teórico"
      - href: modelo.qmd
        text: "Metodología"
      - href: politica.qmd
        text: "Política Pública"

format:
  html:
    theme: cosmo
    math: true