project:
  type: website
  output-dir: docs  # Crítico para GitHub Pages

website:
  title: "Anexo: Economía Espacial y Extractivismo"
  navbar:
    right:
      - href: index.qmd
        text: "Descripción del Problema"
      - href: teoria.qmd
        text: "Marco Teórico"
      - href: modelo.qmd
        text: "Metodología"
      - href: datos.qmd
        text: "Datos"